name: Build Game for iOS
on: workflow_dispatch
jobs:
  iOS:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: Install Libraries
        run: |
          haxelib install hmm --quiet
          haxelib run hmm install --quiet
          haxelib run lime rebuild hxcpp
      - name: Compile
        run: haxelib run lime build ios -nosign -D ONLY_ARM64
      - name: Make .ipa
        run: |
          cd export/*/ios/build/*-iphoneos
          mkdir Payload
          mv *.app Payload
          zip -r Funkin.ipa Payload
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: iOSBuild
          path: export/release/ios/build/Release-iphoneos/*.ipa
          if-no-files-found: error
